name: Andrew Skotzko
brand: Andrew Skotzko
description: Software. Startups. Abundant computing.
keyword:
url: https://andrewskotzko.com
email: andrew@skotzko.com
twitter: askotzko
github: skotzko
stack_overflow: 524750
author: Andrew Skotzko
google_analytics: UA-30368898-1
markdown: kramdown # use pygments instead?
exclude:
  - node_modules

permalink: /:title/
titlecase: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Andrew Skotzko"
      author_url: "https://twitter.com/askotzko"
      comments: true
      body_class: post

# simple_search: https://www.google.com/search

links:
  twitter: https://twitter.com/askotzko
  github: https://github.com/skotzko/
  stack_overflow: https://stackoverflow.com/users/524750/andrews
  instagram: https://instagram.com/skotzko
  rss: /feed.xml

# github pages config
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Disqus Comments
disqus_short_name: skotzko
disqus_show_comment_count: false

# Twitter
twitter_user: askotzko
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: large

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 113895146278122621021
googleplus_hidden: false

# Blog config / pagination
excerpt_link: "Read More &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "/page:num/"


sumo_me_site_id: 6c7e5a264e21bba1b607b7e3368085f29d1477fd0596d25495abc82313033d00
email_list_signup_url: "//thecuriousentrepreneur.us1.list-manage.com/subscribe/post?u=30e2a749f04879b1be678f2a5&amp;id=a428582d45"