name: Andrew Skotzko
brand: Andrew Skotzko
title: Impact entrepreneur & product strategist
title_large_screen: Impact entrepreneur & <br> product strategist
description: Sustainable products + Impact entrepreneurship.
keyword:
url: http://localhost:4000
email: andrew@skotzko.com
twitter: askotzko
github: skotzko
stack_overflow: 524750
author: Andrew Skotzko
google_analytics: UA-30368898-1
analytics: UA-30368898-1 # check —which of these GA vars being used?
year : 2016 # check - being used?
markdown: kramdown # use pygments instead?
exclude:
  - node_modules

debug_mode: true

permalink: /:title/
titlecase: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      comments: false
  -
     scope:
       type: "posts"
     values:
       layout: "post"
       author: "Andrew Skotzko"
       author_url: "https://twitter.com/askotzko"
       comments: false
       body_class: post

# simple_search: https://www.google.com/search

links:
  twitter: https://twitter.com/askotzko
  github: https://github.com/skotzko/
  medium: https://medium.com/@andrewskotzko
  stack_overflow: https://stackoverflow.com/users/524750/andrews
  instagram: https://instagram.com/skotzko
  linkedin: https://www.linkedin.com/in/andrewskotzko
  angel_list: https://angel.co/andrewskotzko
  rss: /feed.xml

# github pages config
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Disqus Comments
disqus_short_name: skotzko
disqus_show_comment_count: false

# Twitter
twitter_user: askotzko
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: large

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 113895146278122621021
googleplus_hidden: false

# Blog config / pagination
excerpt_link: "Read More &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "/page:num/"


sumo_me_site_id: 6c7e5a264e21bba1b607b7e3368085f29d1477fd0596d25495abc82313033d00
email_list_signup_url: "//thecuriousentrepreneur.us1.list-manage.com/subscribe/post?u=30e2a749f04879b1be678f2a5&amp;id=ebe9b14c98"